[package]
name = "rust-nn"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.13.2", features = ["wgpu"] }
instant = "0.1"
ndarray = "0.15"  # For CPU operations
ndarray-rand = "0.14.0"
clap = "3.0"